# Parse html source with race tables ------------------

#' Parse html source with race tables
#'
#' @param css_query_tbl table with year and organization css queries, generated by the function \code{\link{extract_orgs}}.
#' @param remDr Object class remote driver previosly connected using
#' \code{\link{connect_remDr}}.
#'
#' @return list of parsed html options to be used to build queries.
#'
#' @import RSelenium
#' @import rlang

extract_race_table_html <-
  function(css_query_tbl, remDr) {
    year_element <- remDr$findElement(
      using = "css selector",
      value = css_query_tbl$css_query_year)
    # Click year element
    year_element$clickElement()

    temp_orgs <- xml2::read_html(year_element$getPageSource()[[1]]) %>%
      rvest::html_nodes("#organization-selection") %>%
      rvest::html_children()

    #### Check if page is loaded ####

    # Test if the elements of the page have finished loading
    # Create testing object
    test_loading <- stringr::str_detect(rvest::html_text(temp_orgs),"Loading")

    # While loading is still the element being acessed, wait 3 seconds
    # if it is still the same, wait more time.
    # repeat until the while evaluation is FALSE.
    while (TRUE %in% test_loading) {
      # Wait
      Sys.sleep(1)
      # Parse the html again
      temp_orgs <- xml2::read_html(year_element$getPageSource()[[1]]) %>%
        rvest::html_nodes("#organization-selection") %>%
        rvest::html_children()
      # generate new testing string
      test_loading <- stringr::str_detect(
        rvest::html_text(temp_orgs), "Loading")
    }

    #### Organizations query ####

    org_element <- remDr$findElement(
      using = "css selector",
      value = css_query_tbl$css_query_org)

    org_element$clickElement()

    temp_races <- xml2::read_html(org_element$getPageSource()[[1]]) %>%
      rvest::html_nodes("#race-selection") %>%
      rvest::html_children()

    #### Test if page is loaded ####

    test_loading <- stringr::str_detect(
      rvest::html_text(temp_races),"Loading")

    # While loading is still the element being acessed, wait 3 seconds
    # if it is still the same, wait more time.
    # repeat until the while evaluation is FALSE.
    while (TRUE %in% test_loading) {
      # Wait
      Sys.sleep(1)
      # Parse the html again
      temp_races <- xml2::read_html(org_element$getPageSource()[[1]]) %>%
        rvest::html_nodes("#race-selection") %>%
        rvest::html_children()
      # generate new testing string
      test_loading <- stringr::str_detect(
        rvest::html_text(temp_races),"Loading")
    }
    return(temp_races)
  }
