# Start remote driver with docker ---------------------------

#' Start remote driver with docker using the system command line.
#'
#' @param kill Bolean indicating weather a runing docker container with selenium
#' should be killed.
#' @import RSelenium

start_chrome_remDr <- function(kill = TRUE) {
  if(kill == TRUE) {
    system("docker kill `docker ps -q`")
    Sys.sleep(2)
  }
  system("docker run -d -p 4445:4444 --shm-size 2g selenium/standalone-chrome")
  Sys.sleep(2)
  system("docker ps")
  Sys.sleep(2)
}

# connect to remote driver ---------------------------

# This function assumes a docke r container was proviously set up.
# I connects R to the docker container and creates the remDr object that
# ... we can use to interact with websites

#' Connect to remote driver
#'
#' This function assumes a docker container was proviously started using
#' \code{\link{start_chrome_remDr}}. It connects R to the docker container and
#' returns a remote driver object class which is used to interact with websites.
#'
#' @return Object class remote driver.
#' @import RSelenium

connect_remDr <- function() {
  remDr <- RSelenium::remoteDriver(
    remoteServerAddr = "localhost",
    port = 4445L,
    browserName = "chrome")
  return(remDr)
}

# Wrapper function to interact with remote driver ---------------------------

#' Wrapper function to interact with remote driver
#'
#' Wrapper function to do operations with the remote driver. Allows the use of
#' user defined function for a specic link. The idea, is to make the process of
#' remotely interacting with websites, as flexible as possible so that I can
#' pass any function of interest to the scrape or do operations on the
#' link specified.
#'
#' @param remDr remote driver connection object created with
#' \code{\link{connect_remDr}}.
#' @param link url for the website to intereact with.
#' @param FUN user-specified functon
#' @param FUN_input input that will go in \code{FUN}.
#' @return Object generated by \code{FUN}.
#'
#' @import RSelenium

do_remDr <- function(remDr, link, FUN, FUN_input) {
  # Wrapper to start werdriver, oper server connection, move the desired website, do something and close the website in one environment.

  # open server connection
  remDr$open(silent = TRUE)

  # set a timeout
  remDr$setTimeout(type = "Implicit", milliseconds = 5000)

  # navigate to the website
  remDr$navigate(url = link)
  Sys.sleep(2)

  # function to do something on the url
  FUN_output <- FUN(FUN_input)

  # close connection
  remDr$close()

  return(FUN_output)
}

